#pragma checksum "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "470f7856d97edd556cbb111e3c63b7976644dd7f"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Listagem), @"mvc.1.0.view", @"/Views/Home/Listagem.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\_ViewImports.cshtml"
using deliveryfast;

#line default
#line hidden
#nullable disable
#nullable restore
#line 1 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
using deliveryfast.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"470f7856d97edd556cbb111e3c63b7976644dd7f", @"/Views/Home/Listagem.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"e25c30f07b7ca6a1163981e8c2cb87c13f72eb2c", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Listagem : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<List<Cadastro>>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 3 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
  
    ViewData["Title"] = "Pedidos Feitos";

#line default
#line hidden
#nullable disable
            WriteLiteral("<h3>");
#nullable restore
#line 6 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
Write(ViewData["Title"]);

#line default
#line hidden
#nullable disable
            WriteLiteral(@"</h3>
<div class=""row"">
    <div class=""col-md-12"">
        <table class=""table table-striped"" style=""background-color: yellow;"">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Endereço</th>
                    <th>Telefone</th>
                    <th>Tipo de Pão</th>
                    <th>Quantidade</th>
                </tr>
            <tbody>
");
#nullable restore
#line 19 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
                 foreach (Cadastro u in Model)
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <tr>\r\n                        <td>");
#nullable restore
#line 22 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
                       Write(u.Nome);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                        <td>");
#nullable restore
#line 23 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
                       Write(u.Endereco);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                        <td>");
#nullable restore
#line 24 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
                       Write(u.Telefone);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                        <td>");
#nullable restore
#line 25 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
                       Write(u.tipopao);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                        <td>");
#nullable restore
#line 26 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
                       Write(u.Quantidade);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                    </tr>\r\n");
#nullable restore
#line 28 "C:\Users\Alysson Feitosa\Downloads\deliveryfast\Views\Home\Listagem.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("            </tbody>\r\n            </thead>\r\n        </table>\r\n\r\n    </div>\r\n\r\n</div>\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<List<Cadastro>> Html { get; private set; }
    }
}
#pragma warning restore 1591
